### ISSUE TITLE
Update "How to install the chart" section with helm repository installation

### ISSUE THREAD

**Issue by mstein11** [viadee/docker-hub-rate-limit-exporter#10]
The helm chart can now be installed through a helm chart repository hosten on a github page in this repository. We need to describe how that works in the readme. 

```
helm repo add viadee https://viadee.github.io/docker-hub-rate-limit-exporter
helm install viadee/docker-hub-rate-limit-exporter
```

**Comment by mstein11** [comment]
@tlegen-k thanks again for contributing. :-) I had to make some minor adjustments to the readme after merging your PR, but I think now we can close this issue.

**Comment by tlegen-k** [comment]
I'm happy to be of assistance!
