### ISSUE TITLE
Fix wrong reference to ConfigMap in secret checksum

### ISSUE THREAD

**Issue by mstein11** [viadee/docker-hub-rate-limit-exporter#11]
To enable automatic pod replacements on `ConfigMap` and `Secret` changes, we calculate the checksum of those resources and add them as labels to the deployment. However, there is a slight mistake in the deployment.yaml. Line 16 should use the checksum of the `Secret` and not the checksum of the `ConfigMap`.

https://github.com/viadee/docker-hub-rate-limit-exporter/blob/ed587aa84f622eb56dad587572db56ed9db70f57/chart/templates/deployment.yaml#L16

**Comment by 96RadhikaJadhav** [comment]
@mstein11 Can I work on the issue?

**Comment by mstein11** [comment]
Sure, go ahead :-)

**Comment by mstein11** [comment]
Thanks for fixing it! :-)
