### ISSUE TITLE
Make additional podLabels configurable

### ISSUE THREAD

**Issue by jhuebner79** [viadee/docker-hub-rate-limit-exporter#18]
I need to have labels attached to the pods. Many other charts support this. You can get inspired by autoscaler/cluster-autoscaler for example.

**Comment by mstein11** [comment]
Thanks for the suggestions and sorry for the very late reply! I like the idea of having the option to attach labels to the pods. Unfortunately, I don't have the time to implement it right now, but feel free to open a pull request, I'll make sure to swiftly review it if you do. :-)

**Comment by mstein11** [comment]
solved, thanks @Carsten-St !
