### ISSUE TITLE
Requesting images for multiple architectures

### ISSUE THREAD

**Issue by 5nafu** [viadee/docker-hub-rate-limit-exporter#26]
Hi,

first of all: thank you for your effort in creating this monitoring solution.

AWS now offers a great deal on ARM64 instances. If you want to run the exporter on those instances, the pod will (obviously) crash.

Could you please update your build process to create both amd64 and arm64 images? Unfortunately I could not find your current process otherwise I would be very happy to supply a PR.

**Comment by mstein11** [comment]
Hi @5nafu,

thank you for opening this issue. I just created an arm64 image and tagged it with viadee/docker-hub-rate-limit-exporter:version-1.8. I currently do not have an arm64 machine handy, so it is untested, if you want to use it, it would be great if you could report back if everything is working fine. 

To use the new image you will need to set `image.tag: version-1.8` for the values of this helm chat. Once we could verify everything works fine, we will push an update to this repository. 

Best,
Marius

**Comment by 5nafu** [comment]
Hey @mstein11,

looks really good to me, pod is running nicely. A new release would be greatly appreciated. :rocket:


As a side node: 
* I found a missing variable in the `values.yaml`: `hostNetwork`. It is hidden in the templates but not documented. We use it as in an AWS EKS environment the pods get their own public IPv6 address. (That actually took a while to recognize... All looked good in the monitoring :sweat_smile: ) 
* The `tolerations` variable in the `values.yaml` is without function. in the templates it is now divided between `daemonset.tolerations` and `deployment.tolerations`. I am not sure if this is missing in the values file or if the templates should be adjusted.

I would be happy to create a PR for this if you'd like.

**Comment by mstein11** [comment]
Hi @5nafu,

sure, it would be greatly appreciated if you would open a PR for this. If you do so, you could also set the AppVersion in the `Chart.yaml` to version-1.8, to reflect the new docker image. 

For the tolerations, I think it is better to adjust the values file to be compatible with the actual templates, this would ensure backward compatibility, I think. 

Best,
Marius

**Comment by MaxStroh** [comment]
Hi @5nafu,

We are proud to announce, that from image version 1.8.3 and higher, the images are now built and published automatically via github actions - always for both architectures (amd64 and arm64). With this change we also switched to semantic versioning of the images, so don't be confused when looking through the releases:
Releases with a semVer title are the releases of the image, releases with the prefix "docker-hub-rate-limit-exporter-..." are the releases of the helm chart (mainly using the new image per default).

As from now on images are automatically built and pushed for arm64 and amd64 and there was another issue opened for the refactoring of the values I will close this issue as solved.

Greetings,
Max
