### ISSUE TITLE
Please consider publishing image on repository != Docker Hub :-)

### ISSUE THREAD

**Issue by forsberg** [viadee/docker-hub-rate-limit-exporter#30]
Sometimes, we hit the Docker Hub Rate Limit in one of our clusters. The docker-hub-rate-limit-exporter helps us keeping track of what's happening.

However, there's a big irony in the fact that sometimes the docker-hub-rate-limit-exporter can't be pulled because it's on.. Docker Hub, and the limit applies.

Please consider pushing to e.g quay.io, Github Docker Repo (ghcr.io) or Amazon ECR Public Gallery, where rate limits are at least not the same as the one being watched.

**Comment by MaxStroh** [comment]
Hi @forsberg,
thanks for your participation and interest on this topic.

This is actually a good call. We will work on this asap.
I will let you know when there are updates :)

**Comment by MaxStroh** [comment]
Hi @forsberg,
The image is now officially available via AWS ECR registry (see https://gallery.ecr.aws/viadee/docker-hub-rate-limit-exporter).
To use it in your helm chart, set `image.repository` to `public.ecr.aws/viadee/docker-hub-rate-limit-exporter` in your `values.yaml`.
We also added a comment in the default `values.yaml` file, with the alternative image repository.

Thanks for the input! :)
