### ISSUE TITLE
Helm Releaser not finding changes

### ISSUE THREAD

**Issue by mstein11** [viadee/docker-hub-rate-limit-exporter#8]
Currently the helm releaser does not create a new release and outputs:

```
Looking up latest tag...
Discovering changed charts since 'v1.5'...
Nothing to do. No chart changes detected.
```

@shpwrck You have an idea what is going wrong with the current configuration? I'll investigate further probably this evening.

**Comment by shpwrck** [comment]
I think it's related to the bash step I added. Looking at it now.

**Comment by shpwrck** [comment]
#9 

This should fix it.
The chart-release-action was checking the "charts_dir" for changes which didn't exist as far as git was concerned.

**Comment by mstein11** [comment]
Works like a charm. :-) 

I will update the readme and the blogpost in the coming days and then close this issue. Thanks again for contributing :-)

**Comment by mstein11** [comment]
Created a new issue for the update of the documentation => #10
